[graph]
all-features = false

[advisories]
unmaintained = "workspace"
yanked = "warn"
ignore = [
    # примеры:
    # "RUSTSEC-2024-XXXX",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "0BSD",
    "Zlib",
    "CC0-1.0",
    "Unlicense",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
]
confidence-threshold = 0.92

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
