name: Coverage
on:
  push: { branches: [master] }
  pull_request: {}
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate lcov
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --ignore-filename-regex '(^|/)(__tests__|examples|benches)/'

      - name: Make coverage.json
        run: |
          awk -F: '/^LF:/ {lf+=$2} /^LH:/ {lh+=$2} END {pct=(lf?lh/lf*100:0); printf("{\"coverage\": %.2f}\n", pct)}' lcov.info > coverage.json

      - name: Prepare artifact
        run: mkdir -p public/badges && mv coverage.json public/badges/coverage.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
