name: Coverage
on:
  push: { branches: [master] }
  pull_request: {}
permissions:
  contents: write

jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate lcov
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info

      - name: Make coverage.json
        run: |
          awk -F: '/^LF:/ {lf+=$2} /^LH:/ {lh+=$2} END {pct=(lf?lh/lf*100:0); printf("{\"coverage\": %.2f}\n", pct)}' lcov.info > coverage.json

      - name: Publish JSON to gh-pages
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git fetch origin gh-pages || true
          git checkout -B gh-pages
          mkdir -p badges
          mv coverage.json badges/coverage.json
          git add badges/coverage.json
          git commit -m "chore(badge): update coverage [skip ci]" || true
          git push origin gh-pages
